{{- if and .Values.secret.create (not .Values.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "tsmatrix-notify.fullname" .)) .Values.secret.name }}
type: Opaque
stringData:
  MATRIX_ACCESS_TOKEN: {{ .Values.secret.matrixAccessToken | quote }}
  TS3_USER: {{ .Values.secret.ts3User | quote }}
  TS3_PASSWORD: {{ .Values.secret.ts3Password | quote }}
{{- end }}
