apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsmatrix-notify.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tsmatrix-notify.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "tsmatrix-notify.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.config.healthPort }}
      targetPort: http
      protocol: TCP
