from __future__ import annotations

from typing import Callable, Protocol

from tsmatrix_notify.domain.events import TSEvent


class TS3Port(Protocol):
    def version(self) -> str: ...

    def clientlist(self) -> list[dict]: ...

    def clientinfo(self, clid: str) -> dict: ...

    def hostinfo(self) -> dict: ...

    def serverinfo(self) -> dict: ...

    def register_event_handler(self, handler: Callable[[TSEvent], None]) -> None: ...

    def start_keepalive(self) -> None: ...

    def stop_keepalive(self) -> None: ...

    def close(self) -> None: ...

    def reconnect(self) -> None: ...
